#!/bin/bash
# (c) Mats Karlsson 2024-02-01

# Get weather temperature for a city,
# provide the city as an argument to the script

if [ $# -eq 0 ]
  then
    echo "No city added, will guess what city is closest to you."
    echo "or add a city manualy, ex. weather London"
else
    curl -s wttr.in/$1?0?q?T | awk '/°(C|F)/ {printf $(NF-1) $(NF)}' > /home/$USER/.config/weather.txt
    cat /home/$USER/.config/weather.txt
    echo ""
fi
